[env:rpipicow]
platform   = https://github.com/maxgerhardt/platform-raspberrypi.git
board      = rpipicow
framework  = arduino

# IPv4 + Bluetooth (BLE dahil) — Arduino IDE'de "Tools → IP/Bluetooth Stack" ile
# elle seçilmesi gereken ayarın karşılığı. PlatformIO bu satırı otomatik uygular.
board_build.arduino.earlephilhower.ip_bluetooth_stack = ipv4bt

lib_deps =
    adafruit/Adafruit TCS34725@^1.4.0
    adafruit/Adafruit NeoPixel@^1.12.0
